services:
  frontend:
    ports:
      - 8082:80
      - 8083:443

  backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Testing
      - DB__NAME=portfoliosis_test
      - DB__USER=testuser
      - DB__PASSWORD=testpass
    ports:
      - 8080:8080
      - 8081:8081
    
  database:
    environment:
      - POSTGRES_DB=portfoliosis_test
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
    ports:
    - 5432:5432