services:
  frontend:
    image: ghcr.io/snakeinventor/portfoliosis-frontend:latest
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    volumes:
      - ./frontend/certs:/etc/nginx/ssl/certs:ro
    ports:
      - 80:80
      - 443:443