services:
  frontend:
    environment:
      - DEBUG=1
    ports:
      - 8082:80
      - 8083:443

  backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Testing
      - DB__NAME=portfoliosis_test
      - DB__USER=testuser
      - DB__PASSWORD=testpass
    
  database:
    environment:
      - POSTGRES_DB=portfoliosis_test
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
    volumes:
      - /database:/var/lib/postgresql/data