services:
  frontend:
    image: ghcr.io/snakeinventor/portfoliosis-frontend:latest
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    environment:
      - BACKEND_API_URL=http://backend:8080
    volumes:
      - ./frontend/certs:/etc/nginx/ssl/certs:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - DB__HOST=database
      - DB__PORT=5432
      - DB__NAME=portfoliosis
      - DB__USER=${POSTGRES_DB_USER}
      - DB__PASSWORD=${POSTGRES_DB_PASSWORD}
    depends_on:
      - database
  
  database:
    image: postgres:latest
    environment:
      - POSTGRES_DB=portfoliosis
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
    volumes:
      - ./database:/var/lib/postgresql/data