services:
  frontend:
    image: ghcr.io/snakeinventor/portfoliosis-frontend:latest
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    environment:
      - BACKEND_API_URL=https://backend:8081
      - DOMAIN_CERT=portfoliosis.crt
      - DOMAIN_CERT_KEY=portfoliosis.key
      - BACKEND_API_CERT=portfoliosisbackend.pem
    volumes:
      - ./frontend/certs:/etc/nginx/ssl/certs:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend

  backend:
    image: ghcr.io/snakeinventor/portfoliosis-backend:latest
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/certs/portfoliosisbackend.pfx
      - DB__HOST=database
      - DB__PORT=5432
      - DB__NAME=portfoliosis
      - DB__USER=${POSTGRES_DB_USER}
      - DB__PASSWORD=${POSTGRES_DB_PASSWORD}
    volumes:
      - ./backend/certs:/app/certs:ro
    depends_on:
      - database
  
  database:
    image: postgres:latest
    environment:
      - POSTGRES_DB=portfoliosis
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
    volumes:
      - ./database:/var/lib/postgresql/data