# .github/workflows/ci.yml
name: CI Pipeline

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  frontend-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install
      - name: Run lint
        working-directory: ./frontend
        run: npm run lint
  
  backend-build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
    
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
          cache: true
          cache-dependency-path: backend/Portfoliosis.Api/packages.lock.json

      - name: Restore dependencies
        working-directory: ./backend
        run: dotnet restore --locked-mode

      - name: Build
        working-directory: ./backend
        run: dotnet build --no-restore

      - name: Test
        working-directory: ./backend
        run: dotnet test --no-build --verbosity normal
  
  integration-tests:
    needs: [frontend-lint, backend-build-and-test]
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v4

      - name: Write ssl cetificate files to frontend
        working-directory: ./frontend/certs
        env:
          CERT: ${{ secrets.FRONTEND_TEST_CERT }}
          CERTKEY: ${{ secrets.FRONTEND_TEST_CERT_KEY }}
          BACKEND_CERT: ${{ secrets.BACKEND_TEST_CERT }}
        run: |
          echo "$CERT" > ./portfoliosis.crt && echo "$CERTKEY" > ./portfoliosis.key && echo "$BACKEND_CERT" > ./portfoliosisbackend.pem

      - name: Write ssl cetificate files to backend
        working-directory: ./backend/certs
        env:
          BACKEND_CERT_PFX: ${{ secrets.BACKEND_TEST_CERT_PFX }}
        run: |
          echo "$BACKEND_CERT_PFX" | base64 --decode > ./portfoliosisbackend.pfx

      - name: Set up docker compose
        uses: docker/setup-compose-action@v1
        with:
          version: latest
      - name: Build the stack
        run: docker compose -f docker-compose.yaml -f docker-compose-test.yaml build

      - name: Start the stack
        run: docker compose -f docker-compose.yaml -f docker-compose-test.yaml up -d

      - name: Wait until nginx starts
        run: sleep 5

      - name: Run ssl integration test
        env:
          FRONTEND_CERTS: "/frontend/certs"
        run: ./tests.integration/sslTest.sh
      
      - name: Run submit message integration test
        run: ./tests.integration/submitMessageTest.sh
  push-images:
    needs: [integration-tests]
    runs-on: ubuntu-latest

    # Wont run on pull requests
    if: github.event_name == 'push'
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: SnakeInventor
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/snakeinventor/portfoliosis-frontend:latest
            ghcr.io/snakeinventor/portfoliosis-frontend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ghcr.io/snakeinventor/portfoliosis-backend:latest
            ghcr.io/snakeinventor/portfoliosis-backend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
